// Code generated by godddx, DO AVOID EDIT.
package uniqueid

import "github.com/moweilong/chunyu/pkg/orm"

// UniqueID domain model
type UniqueID struct {
	ID        string   `gorm:"primaryKey" json:"id"`                                     // 唯一 id
	CreatedAt orm.Time `gorm:"column:created_at;notNull;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName database table name
func (*UniqueID) TableName() string {
	return "unique_ids"
}
