// Code generated by godddx, DO AVOID EDIT.
package uniqueid

import (
	"context"

	"github.com/moweilong/chunyu/pkg/orm"
)

// UniqueIDStorer Instantiation interface
type UniqueIDStorer interface {
	Find(context.Context, *[]*UniqueID, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *UniqueID, ...orm.QueryOption) error
	Add(context.Context, *UniqueID) error
	Edit(context.Context, *UniqueID, func(*UniqueID), ...orm.QueryOption) error
	Del(context.Context, *UniqueID, ...orm.QueryOption) error
}
