// Code generated by gowebx, DO AVOID EDIT.
package token

import (
	"github.com/moweilong/chunyu/pkg/orm"
	"github.com/moweilong/chunyu/pkg/web"
)

type FindTokenInput struct {
	web.PagerFilter
	UserID    string   `form:"user_id"`    // 用户标识
	Scope     string   `form:"scope"`      // 应用场景
	Hash      []byte   `form:"hash"`       // 发给客户端的令牌 SHA-256 加密
	ExpiredAt orm.Time `form:"expired_at"` // 过期时间
}

type EditTokenInput struct {
	UserID    string   `json:"user_id"`    // 用户标识
	Scope     string   `json:"scope"`      // 应用场景
	Hash      []byte   `json:"hash"`       // 发给客户端的令牌 SHA-256 加密
	ExpiredAt orm.Time `json:"expired_at"` // 过期时间
}

type AddTokenInput struct {
	UserID    string   `json:"user_id"`    // 用户标识
	Scope     string   `json:"scope"`      // 应用场景
	Hash      []byte   `json:"hash"`       // 发给客户端的令牌 SHA-256 加密
	ExpiredAt orm.Time `json:"expired_at"` // 过期时间
}
