// Code generated by gowebx, DO AVOID EDIT.
package token

import (
	"encoding/hex"

	"github.com/moweilong/chunyu/pkg/orm"
)

// Token domain model
type Token struct {
	ID        int      `gorm:"primaryKey" json:"id"`
	UserID    string   `gorm:"column:user_id;notNull;default:'';comment:用户标识" json:"user_id"` // 用户标识
	Scope     string   `gorm:"column:scope;notNull;default:'';comment:应用场景" json:"scope"`     // 应用场景
	Hash      []byte   `gorm:"column:hash;notNull;comment:发给客户端的令牌 SHA-256 加密" json:"hash"`   // 发给客户端的令牌 SHA-256 加密
	CreatedAt orm.Time `gorm:"column:created_at;notNull;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt orm.Time `gorm:"column:updated_at;notNull;default:CURRENT_TIMESTAMP" json:"updated_at"`
	ExpiredAt orm.Time `gorm:"column:expired_at;notNull;default:CURRENT_TIMESTAMP;comment:过期时间" json:"expired_at"` // 过期时间
	Reason    string   `gorm:"column:reason;notNull;default:''" json:"reason"`                                     // 过期原因
}

// TableName database table name
func (*Token) TableName() string {
	return "tokens"
}

// CacheKey 缓存主键，必须唯一
// godddx 生成缓存代码时，依赖的主键
func (t *Token) CacheKey() string {
	return hex.EncodeToString(t.Hash)
}
