// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/moweilong/chunyu/domain/version/versionapi"
	"github.com/moweilong/chunyu/internal/config"
	"github.com/moweilong/chunyu/internal/data"
	"github.com/moweilong/chunyu/internal/web/api"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

func WireApp(bc *config.Bootstrap, log *slog.Logger) (http.Handler, func(), error) {
	db, err := data.SetupDB(bc, log)
	if err != nil {
		return nil, nil, err
	}
	core := versionapi.NewVersionCore(db)
	versionapiAPI := versionapi.New(core)
	uniqueidCore := api.NewUniqueID(db)
	userAPI := api.NewUserAPI(db, uniqueidCore)
	usecase := &api.Usecase{
		Conf:     bc,
		DB:       db,
		Version:  versionapiAPI,
		UniqueID: uniqueidCore,
		UserAPI:  userAPI,
	}
	handler := api.NewHTTPHandler(usecase)
	return handler, func() {
	}, nil
}
