[Server]
  [Server.HTTP]
    Port = 8080
    JwtSecret = ""
    Timeout = "60s"

    [Server.HTTP.Pprof]
      Enabled = true
      AccessIps = ['::1', '127.0.0.1']

[Data]
  [Data.Database]
    # mysql postgres sqlite
    DBType = "mysql"
    # postgres: host=%s port=%s user=%s dbname=%s password=%s sslmode=%s
    # postgres: DSN="host=127.0.0.1 port=5432 user=root dbname=n9e_v6 password=1234 sslmode=disable"
    # mysql: DSN="root:1234@tcp(localhost:3306)/n9e_v6?charset=utf8mb4&parseTime=True&loc=Local"
    # Dsn = './configs/data.db'
    Dsn = 'bugsmo:q185500*@tcp(localhost:3306)/chunyu?charset=utf8mb4&parseTime=True&loc=Local'
    MaxIdleConns = 1
    MaxOpenConns = 1
    ConnMaxLifetime = '6h0m0s'
    SlowThreshold = '200ms'

[Log]
  # 日志存储目录，不能使用特殊符号
  Dir = './logs'
  # 记录级别 debug/info/warn/error
  Level = 'debug'
  # 保留日志多久，超过时间自动删除
  MaxAge = '744h0m0s'
  # 多久时间，分割一个新的日志文件
  RotationTime = '8h0m0s'
  # 多大文件，分割一个新的日志文件(MB)
  RotationSize = 50